# Generated by Django 3.0.7 on 2022-02-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('name', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('address', models.CharField(max_length=64)),
                ('tel', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'tb_userlist',
            },
        ),
    ]
