# Generated by Django 3.0.7 on 2022-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='tel',
        ),
        migrations.AddField(
            model_name='userlist',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
